version: '3.8'

services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tenmo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres1
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tenmo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1
    expose:
      - 5432
    volumes:
      - ./database/tenmo.sql:/docker-entrypoint-initdb.d/tenmo.sql

  react-app:
    image: my-react-app:latest
    ports:
      - 3000:3000  # Assuming your React app runs on port 3000
